# Generated by Django 3.2.16 on 2024-01-14 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240114_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Не менее 1 и не более 720.', validators=[django.core.validators.MaxValueValidator(720, 'Время приготовления не может быть более 720 минут (12.0ч).'), django.core.validators.MinValueValidator(1, 'Время приготовления не может быть менее 1 минуты.')], verbose_name='Время приготовления'),
        ),
    ]
