# Generated by Django 3.2.16 on 2024-01-14 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Не мение 1 минуты и не более 720 минут (12 часов).', validators=[django.core.validators.MaxValueValidator(720, 'Время приготовления не может быть более 720 минут (12 часов).'), django.core.validators.MinValueValidator(1, 'Время приготовления не может быть менее 1 минуты.')], verbose_name='Время приготовления'),
        ),
    ]
