# Generated by Django 3.2.16 on 2024-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipeingredientamount_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Теги для рецепта.', related_name='recipe_tag', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
