# Generated by Django 3.2.16 on 2024-02-02 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Не мение 1 минуты и не более 32000 минут (533 часов) .', validators=[django.core.validators.MaxValueValidator(32000, 'Время приготовления не может быть более 32000 минут (533 часов) .'), django.core.validators.MinValueValidator(1, 'Время приготовления не может быть менее 1 минуты.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Не менее 1 и не более 32000.', validators=[django.core.validators.MaxValueValidator(32000, 'Количество ингредиента не может быть более 32000.'), django.core.validators.MinValueValidator(1, 'Количество ингредиента не может быть менее 1.')], verbose_name='Количество'),
        ),
    ]
