# Generated by Django 3.2.16 on 2024-01-14 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(help_text='Имя аккаунта. Обязательно для заполнения, не более 150 символов.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Имя аккаунта указан не корректно')], verbose_name='Имя аккаунта'),
        ),
    ]
