# Generated by Django 3.2.16 on 2024-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(help_text='Адрес электронной почты. Обязательно для заполнения,  не более 254 символов.', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
