# Generated by Django 3.2.16 on 2024-01-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_foodgramuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user', 'id', 'following'), 'verbose_name': 'Подписки пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('username', 'id', 'email', 'date_joined'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
